name: Code testing
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  operators:
    name: Operators
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Kubebuilder
        run: |
          version=2.3.1 # latest stable version
          arch=amd64
          curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz"
          tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
          mv kubebuilder_${version}_linux_${arch} kubebuilder && sudo mv kubebuilder /usr/local/

      - name: Perform the tests
        working-directory: operators/
        run: |
          make test
          make test-python

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          working-directory: operators/

  operators-generated:
    name: Operators (Generated manifests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Run the automatic generation
        working-directory: operators/
        run: |
          make generate
          make manifests

      - name: Gather the differences
        id: git-diff
        run: |
          output=$(git diff | head -n 100)
          exit_code=$([ "${output}" ] && echo 1 || echo 0)

          # Required to correctly manage multi-line outputs
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"

          echo "::set-output name=diff::${output}"

          # Trigger a failure in case the diff is not empty
          exit ${exit_code}

      - name: Issue a comment in case the diff is not empty
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The generated files in the `operators/` folder appear to be out-of-date.

            Please, ensure you are using the correct version of `controller-gen` and re-run:
            ```
            make generate
            make manifests
            ```

            <details>
              <summary>Here it is an excerpt of the diff:</summary>

              ```diff
              ${{ steps.git-diff.outputs.diff }}
              ```
            </details>
          reactions: confused
        if: failure()


  kubernetes-manifests:
    name: Kubernetes manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Load the example configuration
        run: |
          cat webservice/k8s-manifest-example.env >> $GITHUB_ENV

      - name: Generate the Frontend manifest
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: ./webservice/k8s-manifest.yaml.tmpl
          output: ./webservice/k8s-manifest.yaml

      - name: KubeScore - Frontend
        run: |
          docker run -v ${{ github.workspace }}:/CrownLabs zegl/kube-score score \
              --ignore-test=pod-networkpolicy,container-security-context \
            /CrownLabs/webservice/k8s-manifest.yaml

      - name: Generate the Laboratory Operator manifest
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: ./operators/deploy/laboratory-operator/k8s-manifest.yaml.tmpl
          output: ./operators/deploy/laboratory-operator/k8s-manifest.yaml

      - name: KubeScore - Laboratory Operator
        run: |
          docker run -v  ${{ github.workspace }}:/CrownLabs zegl/kube-score score \
              --ignore-test=pod-networkpolicy \
            /CrownLabs/operators/deploy/laboratory-operator/k8s-manifest.yaml
